### ISSUE TITLE
Events RSS on news site

### ISSUE THREAD

**Issue by aaubryiwu** [iwu/rss-display#1]
All the RSS groups are updated as far as I can tell, but when I tried changing /news/events.html to display only events in the right-hand feed, events from 2015 displayed -- I tried removing 2015 from the group to leave only 2016, & then nothing displays (for now I switched it back to news & events.) Is there something I'm missing to get 2016 events to show up there?

**Comment by michaelcgorman** [comment]
When you switched it from `news-and-events` to `events`, did you also disable the `news` category checkbox? Because I did, and it seems to have worked.

A quick (two-item) perusal of 2016 events vs 2015 events showed me that you don't appear to be including categories in events anymore. So that'd cause only old events to show up.

**Comment by aaubryiwu** [comment]
OK -- Thanks!
